### PR TITLE
here comes all the extra scripts from the x84 repo.

### PR DESCRIPTION
**Pull request by ericolito**

### CODE REVIEW

**Comment by haliphax** [comment]
Please start over -- you've somehow included one of my initial commits in yours, and so there is a merge conflict. Use a branch whenever possible (rather than 'master').

**Comment by ghost** [comment]
Hope the scripts will be available soon ...

**Comment by haliphax** [comment]
I think that these should be hosted outside of this repo -- this repo is more or less just a "phone book" that points to other resources. We could host them one repo per script, or one repo for all of them, or even post each of them as gists and link to them that way. At any rate, this repo will not be storing x84 code.

**Comment by ghost** [comment]
I don't get it - if this repo is not supposed to contain 3rd party addons/extras etc. then why create it in the first place? I agree that extras should be moved outside the official x/84 repo but then the question is: where to put them? If no one wants these scripts anyway, which is the impression I have, then just tell us please.

**Comment by haliphax** [comment]
I think that I thoroughly explained that in my last comment. Scripts should have their own repos, or live in gists -- that way, I'm not responsible for keeping every last one of them up to date. Instead, the _authors_ of those scripts will keep them up to date. This is just a collection of links that point to extra x/84 mods, apps, and resources.

If we posted all of everyone's extra python code here, you wouldn't easily be able to cherry pick the files you wanted using `git` on the command line. Also, it would add a ton of extra (and double) work for me to maintain all of that stuff. You would make a change, then make a pull request, then I would merge it, then you would make another change, etc. etc. etc.

**Pull request closed without merging**
